{{- range .Values.migrations }}
{{- if eq .enable true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name  }}-{{ .db_name | replace "_" "-" }}-migration
  annotations: {}
  labels:
    job: {{ $.Release.Name }}-migration
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrator-container
        image: {{ $.Values.image }}
        command: ["/bin/sh", "-c"]
        args:
            - |
              #!/bin/sh
              apk add git
              echo "git cloning"
              git clone $REPO_URL
              cd $(REPO_NAME)
              # Check out the specific branch
              git checkout $BRANCH_NAME

              # Check out the specific commit hash
              git checkout $COMMIT_HASH

              # Verify that you are on the correct branch and commit
              CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
              CURRENT_COMMIT=$(git rev-parse HEAD)

              echo "Current branch: $CURRENT_BRANCH"
              echo "Current commit: $CURRENT_COMMIT"
              echo "Migrating to version (0 for latest)"
              echo $(MIGRATE_TO_VERSION);
              if [ $(INSTNACE_NAME) -eq "" ]; then
                if [ $(MIGRATE_TO_VERSION) -eq "0" ]; then
                  migrate -path $(SCRIPT_DIR) -database sqlserver://$(DB_USER_NAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(INSTNACE_NAME)?$(QUERY) up;
                else
                  migrate -path $(SCRIPT_DIR) -database sqlserver://$(DB_USER_NAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(INSTNACE_NAME)?$(QUERY) goto $(MIGRATE_TO_VERSION);  
                fi
              else
                if [ $(MIGRATE_TO_VERSION) -eq "0" ]; then
                  migrate -path $(SCRIPT_DIR) -database sqlserver://$(DB_USER_NAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)?$(QUERY) up;
                else
                  migrate -path $(SCRIPT_DIR) -database sqlserver://$(DB_USER_NAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)?$(QUERY) goto $(MIGRATE_TO_VERSION);  
                fi
              fi
        env:
          - name: REPO_URL
            value: {{ .repo_url }}
          - name: BRANCH_NAME
            value: {{ .branch }}
          - name: COMMIT_HASH
            value: {{ .commit }}
          - name: REPO_NAME
            value: {{ .repo_name }}
          - name: SCRIPT_DIR
            value: {{ .location }}
          - name: MIGRATE_TO_VERSION
            value: {{ .version | quote }}
          - name: INSTNACE_NAME
            value: {{ .instance_name }}
          - name: QUERY
            value: {{ .query }}
        envFrom:
          - secretRef:
              name: {{ $.Release.Name  }}-secret
          - configMapRef:
                name: {{ $.Release.Name  }}-configmap
---
{{-  end }}
{{-  end }}