database_credentials:
  db_host: mysql-mysql.devtroncd
  db_password: toKJPt4xjAFAHROMywyJ1Js7vp8Mnzaz
  db_port: "3306"
  db_type: mysql
  db_user: mysql
image: migrate/migrate
migrations:
  - db_name: test
    enable: true
    repo_url: "https://<user>:<token>@github.com/<user>/<repo>.git"
    repo_name: "<repo>"
    branch: "main"
    commit: "2692583b259a17bc3b479b3845c2a85582274157"
    location: scripts/mysql/
    query: "x-tls-insecure-skip-verify=true,multiStatements=true"
    version: "0"